{% set name = "collada-dom" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rdiankov/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3be672407a7aef60b64ce4b39704b32816b0b28f61ebffd4fbd02c8012901e0d
  patches:
    # Backport of https://github.com/rdiankov/collada-dom/pull/43
    - patches/43.patch

build:
  number: 9
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - libboost-devel
    - pcre
    - libxml2
    - zlib
  run:
    - pcre
    - libxml2
    - zlib

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test $PREFIX/include/collada-dom2.5  # [unix]
    - if not exist %PREFIX%\\Library\\include\\collada-dom2.5 exit 1  # [win]

about:
  home: https://sourceforge.net/p/collada-dom

  license: MIT
  license_family: MIT
  license_file: licenses/license_e.txt
  summary: 'The COLLADA Document Object Model (DOM) is an application programming interface (API) that provides a C++ object representation of a COLLADA XML instance document.'

  description: |
    COLLADA is a royalty-free XML schema that enables digital asset exchange within the interactive 3D industry. The COLLADA Document Object Model (COLLADA DOM) is an application programming interface (API) that provides a C++ object representation of a COLLADA XML instance document.
  dev_url: https://sourceforge.net/p/collada-dom

extra:
  recipe-maintainers:
    - jcarpent
    - traversaro

